tasks:
  -
    before: sudo chmod 755 ./scripts/* ./vagrant/*
    init: |
      sudo apt-get update && \
      sudo apt-get install libdevmapper-dev kmod -y && \
      # vagrant
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add - && \
      sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" && \
      sudo apt-get update && \
      sudo apt-get install vagrant
    command: make binary

vscode:
  extensions:
    - pkief.material-icon-theme
    - esbenp.prettier-vscode
    - golang.go
